/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainClassPackage;

import ca.pfv.spmf.algorithms.sequentialpatterns.clospan_AGP.AlgoCloSpan;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStream;
import java.io.Reader;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Map;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import logfile.LogFields;
import logfile.Preprocess;
import project4.MainGuiClass;
import project4.ResultWindow;


/**
 *
 * @author proxc
 */
public class MainGui extends javax.swing.JFrame {
    private boolean isFilled=false;
    final JFileChooser jf;
    File input_file;
    File output_file;
    UserInput u=new UserInput();
    private boolean isFilled1=false;
    private boolean isFilled2;
    private boolean isFilled3;
    private boolean isFilled4;
    public MainGui() {
        jf=new JFileChooser();
        initComponents();
        jLabel9.setVisible(false);
         Result.setVisible(false);
        Session.setVisible(false);
        UserTrans.setVisible(false);
        ViewLog.setVisible(false);
        jPanel8.setVisible(true);
        Prepo.setVisible(false);
        Visual.setVisible(false);
        //RenderChart();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sidebar = new javax.swing.JPanel();
        lbl_west = new javax.swing.JLabel();
        lbl_south = new javax.swing.JLabel();
        lbl_east = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_east1 = new javax.swing.JLabel();
        lbl_east2 = new javax.swing.JLabel();
        lbl_north1 = new javax.swing.JLabel();
        pnl_chart = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnl_table = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Result = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Visual = new javax.swing.JPanel();
        ViewLog = new javax.swing.JPanel();
        jScrollPane2 = new JScrollPane(jTable1, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jTable1 = new javax.swing.JTable();
        Prepo = new javax.swing.JPanel();
        jScrollPane6 = new JScrollPane(jTable1, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jTable2 = new javax.swing.JTable();
        UserTrans = new javax.swing.JPanel();
        jScrollPane4 = new JScrollPane(jTable3, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        ;
        jTable3 = new javax.swing.JTable();
        Session = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane(jTextArea3, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(10, 10));

        pnl_sidebar.setBackground(new java.awt.Color(0, 96, 100));
        pnl_sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_sidebarMouseDragged(evt);
            }
        });
        pnl_sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_sidebarMousePressed(evt);
            }
        });

        lbl_west.setBackground(new java.awt.Color(255, 255, 255));
        lbl_west.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lbl_west.setForeground(new java.awt.Color(0, 153, 153));
        lbl_west.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_west.setText("User Transactions");
        lbl_west.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_west.setOpaque(true);
        lbl_west.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_westMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_westMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_westMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_westMousePressed(evt);
            }
        });

        lbl_south.setBackground(new java.awt.Color(255, 255, 255));
        lbl_south.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lbl_south.setForeground(new java.awt.Color(0, 153, 153));
        lbl_south.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_south.setText("Pre-Processing");
        lbl_south.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_south.setOpaque(true);
        lbl_south.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_southMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_southMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_southMouseExited(evt);
            }
        });

        lbl_east.setBackground(new java.awt.Color(255, 255, 255));
        lbl_east.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lbl_east.setForeground(new java.awt.Color(0, 153, 153));
        lbl_east.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_east.setText("Sessionization");
        lbl_east.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_east.setOpaque(true);
        lbl_east.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_eastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_eastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_eastMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_eastMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 96, 100));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLOSPAN ALGORITHM");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SPMF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(21, 21, 21))
        );

        lbl_east1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_east1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lbl_east1.setForeground(new java.awt.Color(0, 153, 153));
        lbl_east1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_east1.setText("Visualization");
        lbl_east1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_east1.setOpaque(true);
        lbl_east1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_east1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_east1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_east1MousePressed(evt);
            }
        });

        lbl_east2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_east2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lbl_east2.setForeground(new java.awt.Color(0, 153, 153));
        lbl_east2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_east2.setText("Run Algorithm");
        lbl_east2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_east2.setOpaque(true);
        lbl_east2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_east2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_east2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_east2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_east2MousePressed(evt);
            }
        });

        lbl_north1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_north1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lbl_north1.setForeground(new java.awt.Color(0, 153, 153));
        lbl_north1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_north1.setText("View Logfile");
        lbl_north1.setToolTipText("");
        lbl_north1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_north1.setOpaque(true);
        lbl_north1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_north1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_north1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_north1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_sidebarLayout = new javax.swing.GroupLayout(pnl_sidebar);
        pnl_sidebar.setLayout(pnl_sidebarLayout);
        pnl_sidebarLayout.setHorizontalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_south, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_west, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_east, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_east1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_east2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_north1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_sidebarLayout.setVerticalGroup(
            pnl_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_north1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_south, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_west, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_east, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_east1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_east2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pnl_chart.setBackground(new java.awt.Color(0, 96, 100));
        pnl_chart.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_chartMouseDragged(evt);
            }
        });
        pnl_chart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_chartMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INTELLIGENT RECOMMENDATION ");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SYSTEM USING WEB USAGE MINING");

        javax.swing.GroupLayout pnl_chartLayout = new javax.swing.GroupLayout(pnl_chart);
        pnl_chart.setLayout(pnl_chartLayout);
        pnl_chartLayout.setHorizontalGroup(
            pnl_chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_chartLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnl_chartLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_chartLayout.setVerticalGroup(
            pnl_chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_chartLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnl_table.setBackground(new java.awt.Color(255, 255, 255));
        pnl_table.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 96, 100)));
        jPanel9.setPreferredSize(new java.awt.Dimension(270, 200));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(0, 96, 100));
        jPanel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("  Click to browse Logfile");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainClassPackage/Icons/upload (1).png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(85, 85, 85))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 96, 100)));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.setPreferredSize(new java.awt.Dimension(270, 200));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(0, 96, 100));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Click to browse output file\n");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainClassPackage/Icons/upload (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 96, 100)));
        jPanel11.setPreferredSize(new java.awt.Dimension(230, 200));

        jPanel14.setBackground(new java.awt.Color(0, 96, 100));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  MinSup (eg:0.2 or 20%)");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 96, 100));
        jTextField1.setName("minsup"); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 96, 100));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        jButton2.setBackground(new java.awt.Color(0, 96, 100));
        jButton2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 96, 100));
        jButton2.setText("RUN");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, "card2");

        jLabel9.setBackground(new java.awt.Color(0, 96, 100));
        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RUN COMPLETED\n");
        jLabel9.setAlignmentX(1.0F);
        jLabel9.setAlignmentY(1.0F);
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel9, "card3");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        pnl_table.add(jPanel8, "card8");

        Result.setBackground(new java.awt.Color(255, 255, 255));
        Result.setForeground(new java.awt.Color(0, 96, 100));
        Result.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 153, 153));
        jTextArea1.setRows(20);
        jTextArea1.setAlignmentX(1.0F);
        jTextArea1.setAlignmentY(1.0F);
        jTextArea1.setSelectionColor(new java.awt.Color(0, 96, 100));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout ResultLayout = new javax.swing.GroupLayout(Result);
        Result.setLayout(ResultLayout);
        ResultLayout.setHorizontalGroup(
            ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        ResultLayout.setVerticalGroup(
            ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        pnl_table.add(Result, "card7");

        Visual.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout VisualLayout = new javax.swing.GroupLayout(Visual);
        Visual.setLayout(VisualLayout);
        VisualLayout.setHorizontalGroup(
            VisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        VisualLayout.setVerticalGroup(
            VisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        pnl_table.add(Visual, "card6");

        ViewLog.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 96, 100));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.no", "HOST", "TIME", "REQUEST_METHOD", "URL", "STATUS", "REFERRER", "LOC", "USERID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setGridColor(new java.awt.Color(0, 96, 100));
        jTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(0, 96, 100));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(20);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(1).setHeaderValue("HOST");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("REQUEST_METHOD");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("STATUS");
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setHeaderValue("REFERRER");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("LOC");
        }

        javax.swing.GroupLayout ViewLogLayout = new javax.swing.GroupLayout(ViewLog);
        ViewLog.setLayout(ViewLogLayout);
        ViewLogLayout.setHorizontalGroup(
            ViewLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        ViewLogLayout.setVerticalGroup(
            ViewLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLogLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
        );

        pnl_table.add(ViewLog, "card5");

        Prepo.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(0, 96, 100));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.no", "USERID", "TIME", "URL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.setGridColor(new java.awt.Color(0, 96, 100));
        jTable2.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(0, 96, 100));
        jScrollPane6.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(20);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        javax.swing.GroupLayout PrepoLayout = new javax.swing.GroupLayout(Prepo);
        Prepo.setLayout(PrepoLayout);
        PrepoLayout.setHorizontalGroup(
            PrepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrepoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        PrepoLayout.setVerticalGroup(
            PrepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrepoLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );

        pnl_table.add(Prepo, "card4");

        UserTrans.setBackground(new java.awt.Color(255, 255, 255));
        UserTrans.setAutoscrolls(true);

        jTable3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTable3.setForeground(new java.awt.Color(0, 96, 100));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.no", "USER_ID", "URL_SEQUENCE"
            }
        ));
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable3.setDragEnabled(true);
        jTable3.setDropMode(javax.swing.DropMode.ON);
        jTable3.setGridColor(new java.awt.Color(0, 96, 100));
        jTable3.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable3.setMaximumSize(new java.awt.Dimension(2147483647, 1000));
        jTable3.setMinimumSize(new java.awt.Dimension(645, 1000));
        jTable3.setPreferredSize(new java.awt.Dimension(1225, 8000));
        jTable3.setRowHeight(25);
        jTable3.setSelectionBackground(new java.awt.Color(0, 96, 100));
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout UserTransLayout = new javax.swing.GroupLayout(UserTrans);
        UserTrans.setLayout(UserTransLayout);
        UserTransLayout.setHorizontalGroup(
            UserTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserTransLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE)
                .addGap(123, 123, 123))
        );
        UserTransLayout.setVerticalGroup(
            UserTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserTransLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_table.add(UserTrans, "card3");

        Session.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 96, 100));
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        javax.swing.GroupLayout SessionLayout = new javax.swing.GroupLayout(Session);
        Session.setLayout(SessionLayout);
        SessionLayout.setHorizontalGroup(
            SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        SessionLayout.setVerticalGroup(
            SessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        pnl_table.add(Session, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_chart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_table, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx;
    int xy;
    private void pnl_chartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_chartMousePressed
        // TODO add your handling code here:
         xx = evt.getX();
        xy = evt.getY();

    }//GEN-LAST:event_pnl_chartMousePressed

    private void pnl_chartMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_chartMouseDragged
        // TODO add your handling code here:
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);


    }//GEN-LAST:event_pnl_chartMouseDragged

    private void pnl_sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnl_sidebarMousePressed

    private void pnl_sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_sidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnl_sidebarMouseDragged

    private void lbl_westMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_westMousePressed
        // TODO add your handling code here:
        setLblColor(lbl_west);
        resetLblColor(lbl_south);
        resetLblColor(lbl_east);
       
    }//GEN-LAST:event_lbl_westMousePressed

    private void lbl_eastMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eastMousePressed
        // TODO add your handling code here:
        setLblColor(lbl_east);
        resetLblColor(lbl_south);
       
        resetLblColor(lbl_west);
    }//GEN-LAST:event_lbl_eastMousePressed

    private void lbl_east1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_east1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_east1MousePressed

    private void lbl_east2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_east2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_east2MousePressed

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
            // TODO add your handling code here:
            
             int returnvalue = jf.showOpenDialog(MainGui.this);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            
            input_file = jf.getSelectedFile();
            jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainClassPackage/Icons/text-document.png"))); // NOI18N
               jLabel13.setText(input_file.getName()+" Uploaded");
               
        }
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
               int returnvalue = jf.showOpenDialog(MainGui.this);
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            output_file = jf.getSelectedFile();
             jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainClassPackage/Icons/text-document.png"))); // NOI18N
               jLabel1.setText(output_file.getName()+" Uploaded");
               
               
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseClicked
     private void processRunAlgorithmCommandFromGUI() throws FileNotFoundException, IOException, ClassNotFoundException, SQLException {
        // Get the parameters
        String choice = "CloSpan";
        String parameters[] = new String[1];
        parameters[0] = jTextField1.getText();
        if(parameters[0]==""){
        }

    //    textArea.setText("");
        
        // run the selected algorithm
        LogFields logfield = new LogFields();
        System.out.println("Running clospan algorithm...............");
        File f = logfield.logfieldmethod(input_file.getAbsolutePath());

        boolean succeed = runAlgorithm(choice, f.getAbsolutePath(), output_file.getAbsolutePath(), parameters);  // END IF - CHECBOX
     
        if (succeed) {
            Preprocess proc=new Preprocess();
            FileReader fr = new FileReader(output_file);
            BufferedReader br = new BufferedReader(fr);
            
              con=logfield.getConnection();
             Statement stmt = con.createStatement();
                        String line; 
             String tablequery ;
            while ((line = br.readLine()) != null) {
                StringTokenizer Splitter = new StringTokenizer(line, " "); 
                String uline ="";
                while(Splitter.hasMoreTokens()){
                    String s=Splitter.nextToken();
                    if(s=="-1" )
                        continue;
                    if(s.startsWith("#SUP")){
                        uline+="  "+s+" "+Splitter.nextToken();
                        break;
                    }
                    tablequery="select URL FROM UrlMapperData where rownum=1 and URLID LIKE "+s;
                    ResultSet rs=stmt.executeQuery(tablequery);
                    while(rs.next()){
                    uline+=proc.clobToString(rs.getClob(1))+" ";
                    }
                  
                }
              
                jTextArea1.append(uline+"\n");
                
            }
          
              
              jButton2.setVisible(false);
              jLabel9.setVisible(true);
          //  nf.textArea.read(br, null);
            br.close();
           
        }
    }
     
      static class TextAreaOutputStream extends OutputStream {

        JTextArea textArea;

        public TextAreaOutputStream(JTextArea textArea) {
            this.textArea = textArea;
        }

        public void flush() {
            textArea.repaint();
        }

        public void write(int b) {
            textArea.append(new String(new byte[]{(byte) b}));
        }
    }
      private static double getParamAsDouble(String value) {
        if (value.contains("%")) {
            value = value.substring(0, value.length() - 1);
            return Double.parseDouble(value) / 100d;
        }
        return Double.parseDouble(value);
    }
      private static boolean runAlgorithm(String algorithmName, String inputFile, String outputFile, String[] parameters) {
//		System.out.println("C" + algorithmName);

        try {
            // **** CHECK IF ARFF AS INPUT FILE *****
            // FIRST WE WILL CHECK IF IT IS AN ARFF FILE...
            // IF YES, WE WILL CONVERT IT TO SPMF FORMAT FIRST,
            // THEN WE WILL RUN THE ALGORITHM, AND FINALLY CONVERT THE RESULT SO THAT IT CAN
            // BE SHOWED TO THE USER.
            // This map is to store the mapping from ItemID to Attribute value for the conversion
            // from ARFF to SPMF.
            Map<Integer, String> mapItemAttributeValue = null;
            // This variable store the path of the original output file
            String originalOutputFile = null;
            // This variable store the path of the original input file
            String originalInputFile = null;
            // If the file is ARFF
          

            // ****** NEXT WE WILL APPLY THE DESIRED ALGORITHM ******
            // There is a if condition for each algorithm.
            // I will not describe them one by one because it is
            // straightforward.
            if ("CloSpan".equals(algorithmName)) {
                ca.pfv.spmf.algorithms.sequentialpatterns.clospan_AGP.items.creators.AbstractionCreator abstractionCreator = ca.pfv.spmf.algorithms.sequentialpatterns.clospan_AGP.items.creators.AbstractionCreator_Qualitative.getInstance();

                double minSupport = getParamAsDouble(parameters[0]);

                AlgoCloSpan algo = new AlgoCloSpan(minSupport, abstractionCreator, true, true);

                /*
                 * if("".equals(parameters[1]) == false){
                 * algo.setMaximumPatternLength(getParamAsInteger(parameters[1]));
				}
                 */
                ca.pfv.spmf.algorithms.sequentialpatterns.clospan_AGP.items.SequenceDatabase sd = new ca.pfv.spmf.algorithms.sequentialpatterns.clospan_AGP.items.SequenceDatabase();
                sd.loadFile(inputFile, minSupport);

                algo.runAlgorithm(sd, true, false, outputFile);
                System.out.println(algo.printStatistics());

                /////////////////////////////////////////////////////////////end adding by Antonio Gomariz//////////////////////////////////////////////////////////
            }

            // IF THE FILE WAS AN ARFF FILE, WE NEED TO CONVERT BACK THE RESULT
            // SO THAT IT IS PRESENTED IN TERMS OF VALUES
           
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Error. Please check the parameters of the algorithm.  The format for numbers is incorrect. \n"
                    + "\n ERROR MESSAGE = " + e.toString(), "Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        } catch (Throwable e) {
            JOptionPane.showMessageDialog(null,
                    "An error while trying to run the algorithm. \n ERROR MESSAGE = " + e.toString(), "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return false;
        }
        return true;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                    // TODO add your handling code here:
                     try {
            // TODO add your handling code here:
            processRunAlgorithmCommandFromGUI();
        } catch (IOException ex) {
            Logger.getLogger(MainGuiClass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainGuiClass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainGuiClass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lbl_east2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_east2MouseClicked
        // TODO add your handling code here:
        Result.setVisible(true);
        Session.setVisible(false);
        UserTrans.setVisible(false);
        ViewLog.setVisible(false);
        jPanel8.setVisible(false);
        Prepo.setVisible(false);
        Visual.setVisible(false);
        
    }//GEN-LAST:event_lbl_east2MouseClicked
    public String clobToString(Clob data) {
		StringBuilder sb = new StringBuilder();
		try {
			Reader reader = data.getCharacterStream();
			BufferedReader br = new BufferedReader(reader);

			String line;
			while (null != (line = br.readLine())) {
				sb.append(line);
			}
			br.close();
		} catch (SQLException e) {
			// handle this exception
		} catch (IOException e) {
			// handle this exception
		}
		return sb.toString();
	}
    private void lbl_north1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_north1MouseClicked
        // TODO add your handling code here:
         setLblColor(lbl_north1);
        resetLblColor(lbl_east);
        resetLblColor(lbl_east1);
        resetLblColor(lbl_east2);
        resetLblColor(lbl_south);
        resetLblColor(lbl_west);
        if(!isFilled){
           Statement stmt;
           DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        try {
            stmt = con.createStatement();
            String tablequery = "select * from  Weblog";
            ResultSet rs = stmt.executeQuery(tablequery);
            int c=1;
            while (rs.next()) {
			
			String host = rs.getString("HOST");
                        Timestamp timestamp = rs.getTimestamp("TIME");
                        String req = rs.getString("REQUEST_METHOD");
                       String url = clobToString(rs.getClob("URL"));
                        int status=rs.getInt("STATUS");
                        String ref=rs.getString("REFERRER");
                        String loc=rs.getString("LOCATION");
                        String userid = rs.getString("USERID");
			
                        model.addRow(new Object[]{c,host,timestamp.toString(),req,url,status,ref,loc,userid});
			c++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
        }
	
      
         isFilled=true; 
        }  
          Result.setVisible(false);
        Session.setVisible(false);
        UserTrans.setVisible(false);
        ViewLog.setVisible(true);
        jPanel8.setVisible(false);
        Prepo.setVisible(false);
        Visual.setVisible(false);
        
    }//GEN-LAST:event_lbl_north1MouseClicked

    private void lbl_westMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_westMouseClicked
                    // TODO add your handling code here:
                     if(!isFilled1){
           Statement stmt;
           DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
        try {
            stmt = con.createStatement();
            String tablequery = "select * from  SequenceData";
            ResultSet rs = stmt.executeQuery(tablequery);
            int c=1;
            while (rs.next()) {
		       String userid = rs.getString("USERID");
                       String url = clobToString(rs.getClob("URLSequence"));
                        model.addRow(new Object[]{c,userid,url});
			c++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
        }
	
      
         isFilled1=true; 
        }  
          Result.setVisible(false);
        Session.setVisible(false);
        UserTrans.setVisible(true);
        ViewLog.setVisible(false);
        jPanel8.setVisible(false);
        Prepo.setVisible(false);
        Visual.setVisible(false);
        
    }//GEN-LAST:event_lbl_westMouseClicked

    private void lbl_north1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_north1MouseEntered
        // TODO add your handling code here:
        setLblColor(lbl_north1);
        resetLblColor(lbl_east);
        resetLblColor(lbl_east1);
        resetLblColor(lbl_east2);
        resetLblColor(lbl_south);
        resetLblColor(lbl_west);
        
    }//GEN-LAST:event_lbl_north1MouseEntered

    private void lbl_north1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_north1MouseExited
        // TODO add your handling code here:
        resetLblColor(lbl_north1);
    }//GEN-LAST:event_lbl_north1MouseExited

    private void lbl_southMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_southMouseEntered
        // TODO add your handling code here:
        setLblColor(lbl_south);
       
    }//GEN-LAST:event_lbl_southMouseEntered

    private void lbl_southMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_southMouseExited
        // TODO add your handling code here:
        resetLblColor(lbl_south);
    }//GEN-LAST:event_lbl_southMouseExited

    private void lbl_westMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_westMouseEntered
        // TODO add your handling code here:
        setLblColor(lbl_west);
    }//GEN-LAST:event_lbl_westMouseEntered

    private void lbl_westMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_westMouseExited
        // TODO add your handling code here:
        resetLblColor(lbl_west);
    }//GEN-LAST:event_lbl_westMouseExited

    private void lbl_eastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eastMouseEntered
        // TODO add your handling code here:
        setLblColor(lbl_east);
    }//GEN-LAST:event_lbl_eastMouseEntered

    private void lbl_eastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eastMouseExited
        // TODO add your handling code here:
         resetLblColor(lbl_east);
    }//GEN-LAST:event_lbl_eastMouseExited

    private void lbl_east1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_east1MouseEntered
        // TODO add your handling code here:
        setLblColor(lbl_east1);
    }//GEN-LAST:event_lbl_east1MouseEntered

    private void lbl_east1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_east1MouseExited
        // TODO add your handling code here:
         resetLblColor(lbl_east1);
    }//GEN-LAST:event_lbl_east1MouseExited

    private void lbl_east2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_east2MouseEntered
        // TODO add your handling code here:
        setLblColor(lbl_east2);
    }//GEN-LAST:event_lbl_east2MouseEntered

    private void lbl_east2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_east2MouseExited
        // TODO add your handling code here:
        
        resetLblColor(lbl_east2);
    }//GEN-LAST:event_lbl_east2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("http://www.philippe-fournier-viger.com/spmf/index.php?link=documentation.php#clospan"));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lbl_eastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eastMouseClicked
        // TODO add your handling code here:
         if(!isFilled3){
           Statement stmt;
          
        try {
            stmt = con.createStatement();
            String tablequery = "select URLSequence from  SequenceData";
            ResultSet rs = stmt.executeQuery(tablequery);
           
            while (rs.next()) {
		      
                       String url = clobToString(rs.getClob("URLSequence"));
                       
			 jTextArea3.append(url+"\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
        }
	
      
         isFilled3=true; 
        }  
          Result.setVisible(false);
        Session.setVisible(true);
        UserTrans.setVisible(false);
        ViewLog.setVisible(false);
        jPanel8.setVisible(false);
        Prepo.setVisible(false);
        Visual.setVisible(false);
        
    }//GEN-LAST:event_lbl_eastMouseClicked

    private void lbl_southMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_southMouseClicked
        // TODO add your handling code here:
         resetLblColor(lbl_north1);
        resetLblColor(lbl_east);
        resetLblColor(lbl_east1);
        resetLblColor(lbl_east2);
        setLblColor(lbl_south);
        resetLblColor(lbl_west);
        if(!isFilled4){
           Statement stmt;
           DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        try {
            stmt = con.createStatement();
            String tablequery = "select * from  ProcessedData";
            ResultSet rs = stmt.executeQuery(tablequery);
            int c=1;
            while (rs.next()) {
			 String userid = rs.getString("USERID");
                        Timestamp timestamp = rs.getTimestamp("TIME");
                       String url = clobToString(rs.getClob("URL"));
                      
                       
			
                        model.addRow(new Object[]{c,userid,timestamp.toString(),url});
			c++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
        }
	
      
         isFilled4=true; 
        }  
          Result.setVisible(false);
        Session.setVisible(false);
        UserTrans.setVisible(false);
        ViewLog.setVisible(false);
        jPanel8.setVisible(false);
        Prepo.setVisible(true);
        Visual.setVisible(false);
        
    }//GEN-LAST:event_lbl_southMouseClicked

    public void resetLblColor(JLabel lbl) {
        //lbl.setForeground(new Color(255, 255, 255));
        lbl.setBackground(new Color(255,255,255));
        lbl.setForeground(new Color(0,96,100));
    }
    public void setLblColor(JLabel lbl) {
        //lbl.setForeground(new Color(166, 166, 166));
        lbl.setBackground(new Color(0,96,100));
         lbl.setForeground(new Color(255,255,255));
    }

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);

            }
        });
    }
    public Connection con;
     private javax.swing.JTextArea textArea;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Prepo;
    private javax.swing.JPanel Result;
    private javax.swing.JPanel Session;
    private javax.swing.JPanel UserTrans;
    private javax.swing.JPanel ViewLog;
    private javax.swing.JPanel Visual;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_east;
    private javax.swing.JLabel lbl_east1;
    private javax.swing.JLabel lbl_east2;
    private javax.swing.JLabel lbl_north1;
    private javax.swing.JLabel lbl_south;
    private javax.swing.JLabel lbl_west;
    private javax.swing.JPanel pnl_chart;
    private javax.swing.JPanel pnl_sidebar;
    private javax.swing.JPanel pnl_table;
    // End of variables declaration//GEN-END:variables
}
